# Generated by Django 2.1.15 on 2020-04-21 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disks', '0002_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du morceau')),
                ('composer', models.CharField(max_length=100, verbose_name='nom du compositeur')),
                ('milliseconds', models.IntegerField(verbose_name='Durée')),
                ('bytes', models.IntegerField()),
                ('unitprice', models.FloatField(verbose_name='Prix')),
            ],
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=100, verbose_name="Titre de l'album"),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=100, verbose_name="Nom de l'artiste"),
        ),
        migrations.AddField(
            model_name='track',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disks.Album', verbose_name="nom de l'album"),
        ),
    ]
