# Generated by Django 2.1.15 on 2020-04-21 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disks', '0003_auto_20200421_2107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={'verbose_name': 'Morceau'},
        ),
        migrations.AlterField(
            model_name='track',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disks.Album', verbose_name="Nom de l'album"),
        ),
        migrations.AlterField(
            model_name='track',
            name='composer',
            field=models.CharField(max_length=100, verbose_name='Nom du compositeur'),
        ),
    ]
